# Generated by Django 5.0.3 on 2024-03-23 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admins.basemodel')),
                ('name', models.TextField()),
            ],
            bases=('admins.basemodel',),
        ),
        migrations.CreateModel(
            name='AddDelete',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admins.basemodel')),
                ('deleted_at', models.DateField(auto_now=True)),
                ('text_answer_date', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
                ('product_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.product')),
            ],
            bases=('admins.basemodel',),
        ),
        migrations.CreateModel(
            name='ArizaAnswer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admins.basemodel')),
                ('answer_text', models.TextField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.give_offer')),
            ],
            bases=('admins.basemodel',),
        ),
    ]
