# Generated by Django 5.0.3 on 2024-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddelete',
            name='text_answer_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ArizaAnswer',
        ),
    ]
