# Generated by Django 5.0.3 on 2024-03-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        ('user', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddelete',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='adddelete',
            name='product_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.product'),
        ),
    ]
