# Generated by Django 5.0.3 on 2024-03-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
